version: 2.1

orbs:
  docker: circleci/docker@2.1  # Using CircleCI's Docker orb for Docker tasks

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use Node.js 16 Docker image
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true  # Enable Docker layer caching for faster builds
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose-build.yaml build
      - run:
          name: Tag Docker images
          command: |
            docker tag udagram-api-feed nhungntc21/udagram-api-feed:latest
            docker tag udagram-api-user nhungntc21/udagram-api-user:latest
            docker tag udagram-frontend nhungntc21/udagram-frontend:latest
            docker tag reverseproxy nhungntc21/reverseproxy:latest
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker images
          command: |
            docker push nhungntc21/udagram-api-feed
            docker push nhungntc21/udagram-api-user
            docker push nhungntc21/udagram-frontend
            docker push nhungntc21/reverseproxy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build 
