language: node_js
node_js:
  - 16

services:
  - docker

script:
# Build
  - docker-compose -f docker-compose-build.yaml build
# Tag
  - docker tag udagram-api-feed nhungntc21/udagram-api-feed:latest
  - docker tag udagram-api-user nhungntc21/udagram-api-user:latest
  - docker tag udagram-frontend nhungntc21/udagram-frontend:latest
  - docker tag reverseproxy nhungntc21/reverseproxy:latest
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Push
  - docker push nhungntc21/udagram-api-feed
  - docker push nhungntc21/udagram-api-user
  - docker push nhungntc21/udagram-frontend
  - docker push nhungntc21/reverseproxy